### ISSUE TITLE
Upload  local python packages pybamm

### ISSUE THREAD

**Issue by jiawei723** [deepmodeling/dflow#212]
Hi, I am trying to compute some electrochemical problems parallelly in dflow, which needs the python package PyBamm. I followed the user guide and uploaded the local pybamm package:
`from dflow.python import upload_packages`
`upload_packages.append("/home/cfd/anaconda3/lib/python3.9/site-packages/pybamm")`
But it doesn't work. And I put it into some example test case scripts with simple pybamm operations in some OP but no outputs. It still failed.  I think the path is right. If anyone got the similar issue?

**Comment by saltball** [comment]
* First of all, if you are sure that the `PyBamm` package is a necessary dependency for your work, then I suggest you build it into an image before using it. Considering that `PyBamm` also depends on many other packages, this should be the fastest way to solve your problem.

* Taking a step back, if you still want to use the `upload_packages` function, then I suggest you try to **check if `dflow` gives any `ImportError` error or anything else, so that developers and the community can help locate your problem**.

BYW, you may finally find it faster to just make an image containing `PyBamm` and its dependencies.
